[workspace]
members = ["knativity"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.75"
authors = ["Konstantin-Ikaros Kanellopoulos"]
readme = "README.md"
keywords = ["knative", "sdk", "kubernetes"]
